export {default as Home} from "./Home"
export {default as Contact} from "./Contact"
export {default as Work} from "./Projects"
export {default as About} from "./About"
export {default as Skills} from "./Skills"
export {default as Blog} from "./Blog"
export {default as NotFound} from "./404Error"