export {default as Home} from "./Home"
export {default as Services} from "./Services"
export {default as Contact} from "./Contact"
export {default as Work} from "./Work"
export {default as About} from "./About"